/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.crew;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class CrewVueApplication {
    
    public static void main(String[] args) {
        SpringApplication.run(CrewVueApplication.class, args);
    }
}
