spring:
  mustache:
    cache: false
    charset: UTF-8
    prefix: classpath:/static/
    suffix: .html
  h2:    console:      enabled: true
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/testdb
#    username: sa
#    password: 
#    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
logging:
#  config: classpath:log4j2.yml
  level:
    org.hibernate.SQL: debug
    oeg.hibernate.type: trace
server:  port: 8087